### ISSUE TITLE
Use less accurate types to store synapse permances.

### ISSUE THREAD

**Issue by marty1885** [etaler/Etaler#12]
Since HTM is very resistant to noise and the permanence are limited to between 0~1. There is no real reason besides convention to store them as floats. a half, unsigned short or even unsigned char can be enough.

Storing permanence using less bits should make things faster quite a bit.

**Comment by breznak** [comment]
Using coming `bfloat16` or `half` would be exactly for this goal. Esp for your GPU implementation. 
Related issue: https://github.com/htm-community/htm.core/issues/360 
Please let me know if you decide to make some progress on this.

**Comment by marty1885** [comment]
@breznak I have been making trial implementations of this in the past few days, to see what is needed. It is not too high on my priority. My graduation project is due in less than 5 months. And I still have no idea how to get SMI working :stuck_out_tongue: 

Let me know if you are interested to see float16 permanence implemented. I'm going to implementing this sooner or later anyway.

**Comment by breznak** [comment]
> Let me know if you are interested to see float16 permanence implemented.

I definitely am! I've been doing some reading on the existing float16 libraries. Which one are you using? 

I believe it would have reasonable impact for your GPGPU implementation. For our CPU-only c++ htm.core float16 might have no impact, or be actually slower (conversion to float32 for computation), I guess HW support for f16 is only on ARM arch? 

Even better than float would be "custom float type". I was reading in some constants in float.h, but never got it work. I'd like a type that has "hw limited" range (0, 1). So I don't need mantisa. The idea is that the inner-most loops need to check/clamp permanences back to range [0, 1]. If a type ensures this, it'd save costly checks. 

Other idea to explore is use discrete math. Permanence would be `unsigned char`, and inc/dec implemented in multiples of 1/255.

**Comment by marty1885** [comment]
> Which one are you using?
I'm using OpenCL's native half type and the [FP16 repo](https://github.com/Maratyszcza/FP16)

> I guess HW support for f16 is only on ARM arch?
Kinda... ARM CPU's can perform FP16 calculations. But it is not totally IEEE 754 half precision compliant. Newer Intel chips with AVX512 supports [a special kind](https://en.wikichip.org/wiki/brain_floating-point_format) of 16bit floating point values too. 

> Permanence would be unsigned char, and inc/dec implemented in multiples of 1/255.
Sounds interesting! And yeah, I believe this will be the highest performance approach.

**Comment by breznak** [comment]
> native half type and the FP16 repo

I'm testing the FP16 repo, have been able to compile with the headers included. What is actually the name of the float16 type they define? I cannot find it, tried half_t, float16_t, ... Is it in a namespace?

**Comment by marty1885** [comment]
The FP16 repo doesn't provide a float16_t. It stores data in a uint16_t and you perform operations on the uint16_t. I'm definitely switching to another library. Maybe [this one](https://github.com/melowntech/half/blob/master/half/half.hpp). Any suggestions?

**Comment by breznak** [comment]
I have now compiled with `Eigen::half` which I found 
https://github.com/Maratyszcza/FP16/blob/master/third-party/eigen-half.h 
and because we already include Eigen. 

Slight problem is I cannot find any doc on the `Eigen::half`, running on MNIST shows almost none memory reduction (used extreme 12M cols to make it visible). Runtime was tad faster.

**Comment by breznak** [comment]
> Any suggestions?

The answer with "TL;DR" gives a nice list and some details. 

https://stackoverflow.com/questions/5766882/why-is-there-no-2-byte-float-and-does-an-implementation-already-exist 

I likely won't find any good in this for CPU c++: 
https://github.com/acgessler/half_float/issues/3#issuecomment-375895470

I found these: 
https://github.com/minhhn2910/cuda-half2
https://github.com/tianshilei1992/half_precision

with others I have problem that last update is several years ago.

**Comment by marty1885** [comment]
Updating the topic. Unlike https://github.com/htm-community/htm.core/pull/557. There's more I need to do to properly support float16

[ ] Add float16 type information
[ ] float16 tensor operators on the CPU
 [ ] Make HTM algorithm template functions to accept float32 and float16
[ ] float16 tensor operators on the GPU (should be easy)
  [ ] detect weather the GPU have float16 capablity
[ ] Serialize float16

**Comment by marty1885** [comment]
@breznak Have you figured out what happened with your memory usage issue? I'm curious about what's the problem.

**Comment by breznak** [comment]
I haven't experimented much past the first early failure.. 
- FP16 doesn't do what we need
- `Eigen::half` compiled and ran, but at no speed/mem reduction. I cannot find any doc on it whatsoever, so it's kindof a lost case
- tried "uber hack" with using only `char` insted of float32, but carried it only halfway. 
  - we have float32/Real on htm.core codebase
    - Connections.hpp defines `Permanence` (as Real)
  - I cannot easily interchange floating/discrete (char) type in the public intrface (Connections.hpp::Permanence) otherwise naturally many statements break
    - I tried changing `using Permanence = char` internally in Connections.cpp. This compiles, keeps the iterface and does/should internally store using the 1B char. I knew the functionality would be incorrect, as rounding just breaks all to either 0/1.
    - interestingly this ran, but still I saw NO performance/memory improvement. I guess it just added extra conversion to/from char/float, but all operations using Permanence are linked through the header, so converted to float. 

So, probably even the "use char for discrete steps" is not a way, atleast without more several redesign to really take differences in Permanence as char steps everywhere. This will be one path I'd like to finish. 
The other is using another half library, probably from the repo you mention at last `half`.

**Comment by marty1885** [comment]
After cheking all available nvidia GPUs I have (including a RTX 2080Ti). None of them supports the OpenCL extention `cl_khr_fp16`, which enables the use of `half` in OpenCL kernels.

But reports on the internet suggests that 10 and 20 series GeForce GPU should support fp16. I'll have actually try to know weather if Nvidia have a bad list of extensions or the people on the internet is wrong. In the latter case, I'll have to test stuff on Intel iGPUs or get myself a Navi.

**Comment by marty1885** [comment]
Hmm... Maybe the benefit is just not visible on CPUs?

**Comment by breznak** [comment]
>  Maybe the benefit is just not visible on CPUs? 

there won't be computational, until there's HW support for float16 math. I had hoped cache reduction may actually speed things up. But I did not observe even the lesser mem footprint, which should have happened, I must be doing something wrong. 

> None of them supports the OpenCL extention cl_khr_fp16, which enables the use of half

this is really surprising, either openCL is lacking behind on proprietary nvidia (but, nouveau driver would not be suitable for OCL?). Do you get a chance to run the OCL kernel on CUDA? that should definitely support the half.

**Comment by marty1885** [comment]
> this is really surprising, either openCL is lacking behind on proprietary nvidia

My guess is that Nvidia's OpenCL implementation does support fp16 but doesn't list it as supported. There is absolutely no reason not so. <Inset my 2hr rant about how horrible Nvidia's OpenCL implementation is.>

> Do you get a chance to run the OCL kernel on CUDA? that should definitely support the half.

I can, POCL w/ it's CUDA backend will allow me to run OpenCL over CUDA. But POCL's compiler is very not-optimized that any performance benefit from better cache utilization doesn't show up.

**Comment by marty1885** [comment]
Yeah.. The internet definitely says Nvidia Pascal GPUs support fp16. But `clinfo` game me this for the supported extentions.

```
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
```

https://streamhpc.com/blog/2015-09-18/how-to-do-approximation-computing-in-opencl/

**Comment by marty1885** [comment]
**Update**: I have switched to using the [half](https://github.com/ekmett/half) library
But I'm now facing a lot of type casting issue on the CPU C++ side.

**Comment by breznak** [comment]
>  I have switched to using the half library 

do you see seizable performance gain? And on CPU? 

> type casting issue on the CPU C++ side.

does something like `using float = half` work?

**Comment by marty1885** [comment]
> do you see seizable performance gain? And on CPU?
Not yet. I only got the library compilable.

> does something like using float = half work?
No, it's a complicated issue. Etalter heavily uses C++'s type system and TMP to automatically determine the type of the resulting tensor operation. But for some weird reason `half+half = half_percition::result_type` and `half+int = half_percition:: result_type`. Yeah...

**Comment by breznak** [comment]
>  I have switched to using the half library 

does it provide all you need? I think it lacks lot of the overrides for operators, that's why it'd trigger on cpu c++. I'm considering tensorflow's bfloat16 : 
https://github.com/htm-community/htm.core/issues/360#issuecomment-511893650

I gues you won't be interested in their tensors, as you have custom, but still the raw c++ type should be good and well optimized.

**Comment by marty1885** [comment]
> I think it lacks lot of the overrides for operators, that's why it'd trigger on cpu c++. I'm considering tensorflow's bfloat16.

The library does provide operator overrides. But very limited. For example, the half library does support multiplying  a half and a double together, but then it either returns a float or downcasts it into a half. etc...

bfloat16 is also an interesting option but I'm not considering it now as GPUs (at least Intel iGPUs and Navi/Vega series) have native fp16 support. And in the other-hand, implementing bfloat16 on the GPU is going to be a nightmare.

**Comment by marty1885** [comment]
I'm now writing my own float16 class. 

And.. still now sure about what's the case for Nvidia, but now I'm sure that Intel iGPUs does support FP16 and AMD Vega does (not sure about Navi), while AMD Polaris doesn't support fp16.

**Comment by breznak** [comment]
>  Intel iGPUs does support FP16  

for storage and compute? nice. 
I've started extracting bfloat16 headers (and its deps) from TF and publish that. 
Btw, I had no good results with ParallelTS'ing the SP (inhibition) :disappointed:

**Comment by marty1885** [comment]
@breznak I've finished everything besides moving HTM algorithms to fp16.

**Comment by marty1885** [comment]
I've now finally got half working on CPU, in a hacky way. The performance is bad.. Even though it does save me memory, it isn't worth the performance drop.

float:
SpatialPooler
64 bits per SDR, 0.0211828ms per forward
128 bits per SDR, 0.0409088ms per forward
256 bits per SDR, 0.0703682ms per forward
512 bits per SDR, 0.142946ms per forward
1024 bits per SDR, 0.3277ms per forward
2048 bits per SDR, 1.24448ms per forward
9000 bits per SDR, 25.1471ms per forward

float16/half:
SpatialPooler
64 bits per SDR, 0.0290922ms per forward
128 bits per SDR, 0.0510133ms per forward
256 bits per SDR, 0.0985534ms per forward
512 bits per SDR, 0.241993ms per forward
1024 bits per SDR, 0.641391ms per forward
2048 bits per SDR, 2.42902ms per forward
9000 bits per SDR, 54.1216ms per forward

I'll upload the GPU benchmark later.

**Comment by breznak** [comment]
Thanks for the updates! 

> The performance is bad.. Even though it does save me memory, it isn't worth the performance drop.

this aligns with what I've seen with Eigen::half, so my conclusion is: 
Unless there's float16 HW compute instruction support for CPUs, this optimization actually degrades performance.

**Comment by marty1885** [comment]
It is a sad truth. But I can't grasp why using char doesn't save memory in your case. That's really weird.

**Comment by breznak** [comment]
>  why using char doesn't save memory in your case. That's really weird. 

I guess it's because I did the change only in internal (cpp) code, not on the public hpp, so all computations would have convert to/from float-char. I may retry that experiment properly.

**Comment by marty1885** [comment]
Apparently NVIDIA hates OpenCL. `cl_khr_fp16` is not usable on my GTX 1050 (Yeah... I got a lot of GPUs). Even trying to force enabling it.
Excluding mobile processors, the only GPUs that support FP16 are: AMD Vega, AMD Navi, Intel 9th Gen (which I do own.)

Great.

**Comment by breznak** [comment]
> Apparently NVIDIA hates OpenCL 

yes, :(

**Comment by marty1885** [comment]
The optimization is totally worth the while on a GPU tho.

FP16 on Intel iGPU:
64 bits per SDR, 0.117742ms per forward
128 bits per SDR, 0.142358ms per forward
256 bits per SDR, 0.204964ms per forward
512 bits per SDR, 0.351912ms per forward
1024 bits per SDR, 0.825706ms per forward
2048 bits per SDR, 3.85969ms per forward

FP32 on Intel iGPU:
64 bits per SDR, 0.119128ms per forward
128 bits per SDR, 0.123414ms per forward
256 bits per SDR, 0.179358ms per forward
512 bits per SDR, 0.321207ms per forward
1024 bits per SDR, 0.876803ms per forward
2048 bits per SDR, 5.35717ms per forward

float16 is 40% faster than float32!

**Comment by breznak** [comment]
> float16 is 40% faster than float32! 

great to hear, and congratz! :clap: 
And the memory footprint is also reduced as expected? 

Pity this does not (yet) apply to CPUs

**Comment by marty1885** [comment]
> And the memory footprint is also reduced as expected?
It does. Saving me 25% of memory by converting from float to half. (I'm still using 32bit integers for indices, which will be the next thing I'll optimize)

**Comment by marty1885** [comment]
Now the feature is implemented. I'll close the issue.
Feel free to re-open it if anyone wants to ask stuff or want additional information.
