### ISSUE TITLE
Docker build not pulling the latest source code.

### ISSUE THREAD

**Issue by marty1885** [etaler/Etaler#4]
Related to #3 

After pushing f3f6bb62a63e9a8b5bb0c60a39a5ccb9e711d95d to master, fixing containerized build. `./build.sh` is still cloning and pulling from a92ac485e1dcc50f47b5baa2305986fe716d4013 even after removing the build container.

c.c. @alior101

**Comment by alior101** [comment]
That's because of Dockers cache.. It doesnt know that version changed ... I will find a solution for that ..

**Comment by marty1885** [comment]
Thank you! fixed. #6
