### ISSUE TITLE
why own llvm smallvector implementation ?

### ISSUE THREAD

**Issue by alior101** [etaler/Etaler#55]
Hi Martin,
Can you please explain why you had to modify smallvec from the default llvm implementation ? Why not use the original unmodified one ?
Thanks
Lior

**Comment by marty1885** [comment]
Hi,
Because LLVM is a super huge dependency and what I really need is smallvec. And I don't expect everyone have LLVM installed on their system. Especially on Windows.

**Comment by alior101** [comment]
ok. I adapted llvm pretty print for smallvec to ur impl - now it finally looks like normal array :) . I'll PR it in the next batch of changed..
![20190804_172836](https://user-images.githubusercontent.com/3033580/62424875-86f8f100-b6dd-11e9-82b2-3b1380b00075.jpg)
