### ISSUE TITLE
Visualization of the SDR for higher level functionality debug

### ISSUE THREAD

**Issue by alior101** [etaler/Etaler#7]
We need some kind of visualization to understand what's going on inside the model. This is especially true for grid cells setups...  Any easy to integrate c++ graphics lib like in htm path ?

**Comment by marty1885** [comment]
I think we need something like matplotlib but supports realtime ploting. There's look like barely anything like it in C++.

Well... I use [imgui](https://github.com/ocornut/imgui) + [SFML](https://www.sfml-dev.org/) with [a very hacky SDR display function](https://github.com/marty1885/HTMPath/blob/9210b97db86bf50e2e12399e3bf5df79e1d08b13/main.cpp#L31-L61) in HTMPath. It is really not ideal for something that will be reused.

I find myself using [ROOT](https://root.cern.ch/) a lot to build, experiment and plot new layers. But ROOT is a very heavy dependency..

ArrayFire's [graphics module](http://arrayfire.org/arrayfire-python/arrayfire.graphics.html) is also easy to integrate. But again ArrayFire is very heavy dependency.

After some googling, [matplotlib-cpp](https://github.com/lava/matplotlib-cpp) seems to be a good solution but we'll have to link to Python. [PLplot](http://plplot.sourceforge.net/) looks like a good solution but I'm not familiar with it.

On a related note. We could build a Python wrapper and do experiments in the python world. It's on the roadmap and we'll have to make one some day. But I think it is way too much work for now.

What do you think?

**Comment by alior101** [comment]
Let me look at the options ... I like matplotlib-cpp need to play with it a
little to see how it plots in real time .. I'll you know once I have
something to show

**Comment by marty1885** [comment]
I guess this have been solved since #39 have been merged? Closing. Feel free to reopen.
