### ISSUE TITLE
Providing operator [] for et::Tensor (or at least a better way to handle tensor subscription)

### ISSUE THREAD

**Issue by marty1885** [etaler/Etaler#71]
Numpy's way of doing ND array subscription is widely accepted and straight forward.

ex:
```python
>>> a = np.zeros(4,4)
>>> a[:2, :2]
```

Due to the fact that C++'s `operator []` can only take *one* argument. I ended up implementing a `view()` method to perform subscription.

ex:
```c++
[cling]$ auto a = ones({4,4})
[cling]$ a.view({range(2), range(2)})
```

But TBH, it gets annoying when I start to write more code with it. It would be great to have a [] equivalent in Etaler. We have a few solution. 

1. make `Tensor Tensor::operator [] (svector<Range>)`

Which will allow us to do

```c++
[cling]$ auto a = ones({4,4})
[cling]$ a[{range(2), range(2)})]
```

There is an extra bracket around the parameters.

2. make `Tensor Tensor::operator [] (svector<Range>)` and overload `Range::operator , ()`

Which allows us to

```c++
[cling]$ auto a = ones({4,4})
[cling]$ a[range(2), range(2))]
```

It gives us the syntax we want. But messes with how C++ evaluates values.

3. Use `operator ()`

This is ArrayFire's solution. It feels weird to subscript using () instead of [].

```c++
[cling]$ auto a = ones({4,4})
[cling]$ a(range(2), range(2)))
```

It feels like calling a function....

Any ideas?

**Comment by alior101** [comment]
I'm voting for option 1 :)

**Comment by marty1885** [comment]
@alior101 should be implemented now :)
