### ISSUE TITLE
Show both active and predictive cells in visualzer

### ISSUE THREAD

**Issue by marty1885** [etaler/Etaler#76]
I'm now debugging a weird behavior in the TM, but tmviz was built for tiny-htm so it won't work on Etaler. 

@alior101 Your visualizer have been very helpful in the process. Would you mind spending a minute making the visualizer also show cells in the predictive state?

**Comment by alior101** [comment]
Hi Martin,
I'll be very busy next week at work ... I'll try to give it few cycles the
week after ..

**Comment by marty1885** [comment]
Thank you! Pardon for bordering you when your are the busiest.
